### ISSUE TITLE
Skills items are not readable

### ISSUE THREAD

**Issue by adriana-olszak** [angelika7/portfolioV2#3]
![image](https://user-images.githubusercontent.com/17515394/104964553-e97ea380-59dc-11eb-8a4b-4e4ac528b0b2.png)

As it can be seen on the attached image text in the skills section is not readable. 

Changing it to smth like this may increase the readability of this section. 
![image](https://user-images.githubusercontent.com/17515394/104964850-99eca780-59dd-11eb-91ef-1771a2c974e0.png)

```css
.toolItem__TextBox__1SFjD {
    height: 100%;
    padding-bottom: 1.5rem;
    display: flex;
    flex-direction: row;
    justify-content: center;
    align-items: center;
}
```

I want to put emphasis on the Typography of your webpages. Throughout the years of first - print media (newspapers, posters, etc) and the internet media (websites, applications, etc) we agreed on a set of rules that are pleasing for the majority of the people that are using the web. 
There is an awesome chapter on Typography in the Refactoring UI book that I shared with you. I highly recommend reading it and applying the rules to your designs. As a future FrontEnd developer, you should have a very high-level understanding of trends used in UI design. That knowledge would be used in your day to day work with designers and other members of the team. 

Another good source of Typography rules that you broke in your repository: https://www.webdesignerdepot.com/2020/07/the-designers-guide-to-letter-spacing/
